apiVersion: v1
kind: Secret
metadata:
  name: canteen-secret
  namespace: canteen-hub
type: Opaque
stringData:
  DB_USERNAME: "canteen_user"
  DB_PASSWORD: "canteen_secure_pass123"
  DB_ROOT_PASSWORD: "root_secure_pass123"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
