import { Category, MenuItem } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 1, name: 'Breakfast', description: 'Start your day right with our nutritious breakfast options', active: true },
  { id: 2, name: 'Lunch', description: 'Hearty meals for your midday break', active: true },
  { id: 3, name: 'Snacks', description: 'Light bites to keep you energized', active: true },
  { id: 4, name: 'Beverages', description: 'Refreshing drinks, hot and cold', active: true },
  { id: 5, name: 'Specials', description: 'Chef specials and seasonal favorites', active: true },
];

export const DEFAULT_MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato masala, served with sambar and chutney',
    price: 80.0,
    categoryId: 1,
    categoryName: 'Breakfast',
    available: true,
    vegetarian: true,
    rating: 4.5,
    ratingCount: 120,
    preparationTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 2,
    name: 'Idli Sambar',
    description: 'Soft steamed rice cakes served with piping hot sambar and fresh coconut chutney',
    price: 40.0,
    categoryId: 1,
    categoryName: 'Breakfast',
    available: true,
    vegetarian: true,
    rating: 4.3,
    ratingCount: 95,
    preparationTime: 8,
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 3,
    name: 'Medu Vada',
    description: 'Crispy lentil doughnuts served with sambar and chutney',
    price: 30.0,
    categoryId: 1,
    categoryName: 'Breakfast',
    available: true,
    vegetarian: true,
    rating: 4.2,
    ratingCount: 80,
    preparationTime: 8,
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 4,
    name: 'Upma',
    description: 'Savory semolina porridge with vegetables and spices',
    price: 45.0,
    categoryId: 1,
    categoryName: 'Breakfast',
    available: true,
    vegetarian: true,
    rating: 4.0,
    ratingCount: 60,
    preparationTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 5,
    name: 'Kesari Bath',
    description: 'Sweet saffron-flavored semolina pudding with ghee',
    price: 35.0,
    categoryId: 1,
    categoryName: 'Breakfast',
    available: true,
    vegetarian: true,
    rating: 4.4,
    ratingCount: 75,
    preparationTime: 8,
    imageUrl: '/images/kesari-bath.png',
  },
  {
    id: 6,
    name: 'Pulao',
    description: 'Fragrant basmati rice cooked with mixed vegetables and aromatic spices',
    price: 90.0,
    categoryId: 2,
    categoryName: 'Lunch',
    available: true,
    vegetarian: true,
    rating: 4.1,
    ratingCount: 55,
    preparationTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 7,
    name: 'Dal Tadka',
    description: 'Yellow lentils tempered with cumin, garlic and spices, served with rice',
    price: 75.0,
    categoryId: 2,
    categoryName: 'Lunch',
    available: true,
    vegetarian: true,
    rating: 4.3,
    ratingCount: 65,
    preparationTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 8,
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese in rich tomato-butter gravy, best with naan',
    price: 130.0,
    categoryId: 2,
    categoryName: 'Lunch',
    available: true,
    vegetarian: true,
    rating: 4.7,
    ratingCount: 110,
    preparationTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 9,
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with tender chicken and whole spices',
    price: 160.0,
    categoryId: 2,
    categoryName: 'Lunch',
    available: true,
    vegetarian: false,
    rating: 4.8,
    ratingCount: 200,
    preparationTime: 25,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 10,
    name: 'Egg Fried Rice',
    description: 'Wok-tossed rice with scrambled eggs, vegetables and soy sauce',
    price: 100.0,
    categoryId: 2,
    categoryName: 'Lunch',
    available: true,
    vegetarian: false,
    rating: 4.2,
    ratingCount: 90,
    preparationTime: 15,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 11,
    name: 'Samosa',
    description: 'Crispy pastry filled with spiced potatoes and peas, served with mint chutney',
    price: 20.0,
    categoryId: 3,
    categoryName: 'Snacks',
    available: true,
    vegetarian: true,
    rating: 4.5,
    ratingCount: 180,
    preparationTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 12,
    name: 'Bread Pakoda',
    description: 'Bread slices dipped in spiced chickpea batter and deep fried',
    price: 25.0,
    categoryId: 3,
    categoryName: 'Snacks',
    available: true,
    vegetarian: true,
    rating: 4.1,
    ratingCount: 70,
    preparationTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 13,
    name: 'Poha',
    description: 'Flattened rice cooked with onions, mustard seeds, and curry leaves',
    price: 30.0,
    categoryId: 3,
    categoryName: 'Snacks',
    available: true,
    vegetarian: true,
    rating: 4.0,
    ratingCount: 55,
    preparationTime: 8,
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 14,
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea with ginger, cardamom and milk',
    price: 20.0,
    categoryId: 4,
    categoryName: 'Beverages',
    available: true,
    vegetarian: true,
    rating: 4.6,
    ratingCount: 250,
    preparationTime: 3,
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 15,
    name: 'Cold Coffee',
    description: 'Blended iced coffee with milk and sugar',
    price: 60.0,
    categoryId: 4,
    categoryName: 'Beverages',
    available: true,
    vegetarian: true,
    rating: 4.4,
    ratingCount: 130,
    preparationTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 16,
    name: 'Fresh Lime Soda',
    description: 'Freshly squeezed lime with soda water, sweet or salted',
    price: 30.0,
    categoryId: 4,
    categoryName: 'Beverages',
    available: true,
    vegetarian: true,
    rating: 4.3,
    ratingCount: 95,
    preparationTime: 3,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 17,
    name: 'Mango Lassi',
    description: 'Chilled yogurt drink blended with fresh mango pulp',
    price: 55.0,
    categoryId: 4,
    categoryName: 'Beverages',
    available: true,
    vegetarian: true,
    rating: 4.7,
    ratingCount: 160,
    preparationTime: 5,
    imageUrl: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 18,
    name: 'Thali Special',
    description: 'Complete meal with dal, sabzi, rice, roti, salad and dessert',
    price: 150.0,
    categoryId: 5,
    categoryName: 'Specials',
    available: true,
    vegetarian: true,
    rating: 4.9,
    ratingCount: 85,
    preparationTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 19,
    name: 'Chef Special Pasta',
    description: 'Penne pasta in homemade tomato basil sauce with herbs',
    price: 120.0,
    categoryId: 5,
    categoryName: 'Specials',
    available: true,
    vegetarian: true,
    rating: 4.2,
    ratingCount: 45,
    preparationTime: 20,
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 20,
    name: 'Chaat Platter',
    description: 'Assorted street food bites: pani puri, bhel puri and sev puri',
    price: 70.0,
    categoryId: 5,
    categoryName: 'Specials',
    available: true,
    vegetarian: true,
    rating: 4.6,
    ratingCount: 100,
    preparationTime: 10,
    imageUrl: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=600&q=80',
  },
];
